MAX_CHARS_PER_LINE = 42
MAX_LINES_PER_SUBTITLES = 2
MAX_CHARS_PER_SECOND = 21

POINTS_FOR_CORRECT_VOTING = 1
POINTS_FOR_BEING_VOTED = 1
POINTS_FOR_EXACT_GUESSING = 1

INSTRUCTION_URL_IT = 'https://telegra.ph/Plagio---Regole-del-gioco-01-06'
INSTRUCTION_URL_EN = 'https://telegra.ph/Plagio---Game-Rules-01-06'
