MIN_NUM_OF_PLAYERS = 2

MIN_BEGINNING_LENGTH = 10
MIN_TEXT_INFO_LENGTH = 10

MAX_NUM_HANDS = 100

POINTS = {
    'CREATIVITY': {
        'CORRECT_VOTING': 1,
        'POINTS_PER_RECEIVED_VOTE': 1,
        'EXACT_GUESSING': 1
    },
    'EXACTNESS': {
        'CORRECT_VOTING': 1,
        'POINTS_PER_RECEIVED_VOTE': 0,
        'EXACT_GUESSING': 2
    }
}

INSTRUCTION_URL_IT = 'https://telegra.ph/Plagio---Regole-del-gioco-01-06'
INSTRUCTION_URL_EN = 'https://telegra.ph/Plagio---Game-Rules-01-06'

EXPIRATION_DELTA_HOURS = 24
EXPIRATION_DELTA_MILLISECONDS = EXPIRATION_DELTA_HOURS * 3600 * 1000